### ISSUE TITLE
fetchnwp not catching empty (0 kB) .grib2 files

### ISSUE THREAD

**Issue by williamhobbs** [SolarArbiter/solarforecastarbiter-core#696]
If I make too many requests to NOMADS, it will start returning 0 kB .grib2 files. In some cases, `solararbiter fetchnwp`  does not seem to notice this and proceeds to create a .nc file that is missing data. It seems like having a way to either 

1. return a warning or error, or 
2. catch this issue, delete empty files, and re-download them, 

would be helpful. 

Details on an example test case are below, where I tried fetching gefs while also fetching hrrr_subhourly. The easy solution here is that I shouldn't fetch gefs while running other fetch processes, but it seems possible that this same issue could come up in unavoidable ways, e.g., after a multi-day network outage and `solararbiter fetchnwp` catches up all at once when the network comes back.

- I have a regular existing process running, `solararbiter fetchnwp -v /home/pi/Downloads/sfa hrrr_subhourly'
- I started a test process at ~ 2021-07-23 15:58 UTC, `solararbiter fetchnwp -v /home/pi/Downloads/sfa gefs`, and quickly started being throttled by NOAA, receiving 0 kB files
- 'fetchnwp' had already started on `hrrr_subhourly`. This resulted in getting 0 kB hrrr files being downloaded:
- ls -l output part of the way through fetching (note the empty files for f04-f06):
```
pi@raspberrypi:~/Downloads/sfa/hrrr_subhourly/2021/07/23/15 $ ls -l
total 23088
-rw-r--r-- 1 pi pi  705980 Jul 23 15:51 hrrr.t15z.wrfsubhf00.grib2
-rw-r--r-- 1 pi pi 2814134 Jul 23 15:53 hrrr.t15z.wrfsubhf01.grib2
-rw-r--r-- 1 pi pi 2549912 Jul 23 15:55 hrrr.t15z.wrfsubhf02.grib2
-rw-r--r-- 1 pi pi 2559698 Jul 23 15:58 hrrr.t15z.wrfsubhf03.grib2
-rw-r--r-- 1 pi pi       0 Jul 23 15:59 hrrr.t15z.wrfsubhf04.grib2
-rw-r--r-- 1 pi pi       0 Jul 23 15:59 hrrr.t15z.wrfsubhf05.grib2
-rw-r--r-- 1 pi pi       0 Jul 23 15:59 hrrr.t15z.wrfsubhf06.grib2
-rw-r--r-- 1 pi pi 2677130 Jul 23 16:08 hrrr.t15z.wrfsubhf07.grib2
-rw-r--r-- 1 pi pi 2784776 Jul 23 16:08 hrrr.t15z.wrfsubhf08.grib2
-rw-r--r-- 1 pi pi 2628200 Jul 23 16:10 hrrr.t15z.wrfsubhf09.grib2
-rw-r--r-- 1 pi pi 2510768 Jul 23 16:12 hrrr.t15z.wrfsubhf10.grib2
-rw-r--r-- 1 pi pi  759074 Jul 23 16:14 hrrr.t15z.wrfsubhf11.grib2
-rw-r--r-- 1 pi pi  749288 Jul 23 16:16 hrrr.t15z.wrfsubhf12.grib2
-rw-r--r-- 1 pi pi  710144 Jul 23 16:18 hrrr.t15z.wrfsubhf13.grib2
-rw-r--r-- 1 pi pi  749288 Jul 23 16:20 hrrr.t15z.wrfsubhf14.grib2
-rw-r--r-- 1 pi pi  710144 Jul 23 16:22 hrrr.t15z.wrfsubhf15.grib2
-rw-r--r-- 1 pi pi  710144 Jul 23 16:24 hrrr.t15z.wrfsubhf16.grib2
```

- ls -l output after convertsion to NetCDF finished (~18 MB .nc file):
```
pi@raspberrypi:~/Downloads/sfa/hrrr_subhourly/2021/07/23/15 $ ls -l
total 18448
-rw-r--r-- 1 pi pi 18888249 Jul 23 16:28 hrrr_subhourly.nc
```

- fetchnwp verbose output (warnings issued for f03, f07, f08, but not the empty files f04-f06):
```
2021-07-23 15:27:29,272 INFO Sleeping 1050.7s for next model run 
2021-07-23 15:51:01,371 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf00.grib2
2021-07-23 15:53:01,759 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf01.grib2
2021-07-23 15:55:02,064 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf02.grib2
2021-07-23 15:57:02,467 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf03.grib2
2021-07-23 15:57:02,694 WARNING Request to https://nomads.ncep.noaa.gov/cgi-bin/filter_hrrr_sub.pl?file=hrrr.t15z.wrfsubhf03.grib2&dir=/hrrr.20210723/conus&lev_2_m_above_ground=on&lev_10_m_above_ground=on&lev_entire_atmosphere=on&lev_surface=on&var_DSWRF=on&var_VBDSF=on&var_VDDSF=on&var_TMP=on&var_WIND=on&subregion=&leftlon=-90.5&rightlon=-80.5&toplat=35.2&bottomlat=30 failed with code 404, retrying
2021-07-23 15:59:02,802 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf04.grib2
2021-07-23 15:59:03,021 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf05.grib2
2021-07-23 15:59:03,240 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf06.grib2
2021-07-23 15:59:03,459 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf07.grib2
2021-07-23 15:59:03,695 WARNING Request to https://nomads.ncep.noaa.gov/cgi-bin/filter_hrrr_sub.pl?file=hrrr.t15z.wrfsubhf07.grib2&dir=/hrrr.20210723/conus&lev_2_m_above_ground=on&lev_10_m_above_ground=on&lev_entire_atmosphere=on&lev_surface=on&var_DSWRF=on&var_VBDSF=on&var_VDDSF=on&var_TMP=on&var_WIND=on&subregion=&leftlon=-90.5&rightlon=-80.5&toplat=35.2&bottomlat=30 failed with code 404, retrying
2021-07-23 16:00:04,155 WARNING Request to https://nomads.ncep.noaa.gov/cgi-bin/filter_hrrr_sub.pl?file=hrrr.t15z.wrfsubhf07.grib2&dir=/hrrr.20210723/conus&lev_2_m_above_ground=on&lev_10_m_above_ground=on&lev_entire_atmosphere=on&lev_surface=on&var_DSWRF=on&var_VBDSF=on&var_VDDSF=on&var_TMP=on&var_WIND=on&subregion=&leftlon=-90.5&rightlon=-80.5&toplat=35.2&bottomlat=30 failed with code 404, retrying
2021-07-23 16:01:04,049 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf08.grib2
2021-07-23 16:01:04,362 WARNING Request to https://nomads.ncep.noaa.gov/cgi-bin/filter_hrrr_sub.pl?file=hrrr.t15z.wrfsubhf08.grib2&dir=/hrrr.20210723/conus&lev_2_m_above_ground=on&lev_10_m_above_ground=on&lev_entire_atmosphere=on&lev_surface=on&var_DSWRF=on&var_VBDSF=on&var_VDDSF=on&var_TMP=on&var_WIND=on&subregion=&leftlon=-90.5&rightlon=-80.5&toplat=35.2&bottomlat=30 failed with code 404, retrying
2021-07-23 16:01:04,500 WARNING Request to https://nomads.ncep.noaa.gov/cgi-bin/filter_hrrr_sub.pl?file=hrrr.t15z.wrfsubhf07.grib2&dir=/hrrr.20210723/conus&lev_2_m_above_ground=on&lev_10_m_above_ground=on&lev_entire_atmosphere=on&lev_surface=on&var_DSWRF=on&var_VBDSF=on&var_VDDSF=on&var_TMP=on&var_WIND=on&subregion=&leftlon=-90.5&rightlon=-80.5&toplat=35.2&bottomlat=30 failed with code 404, retrying
2021-07-23 16:02:06,376 WARNING Request to https://nomads.ncep.noaa.gov/cgi-bin/filter_hrrr_sub.pl?file=hrrr.t15z.wrfsubhf07.grib2&dir=/hrrr.20210723/conus&lev_2_m_above_ground=on&lev_10_m_above_ground=on&lev_entire_atmosphere=on&lev_surface=on&var_DSWRF=on&var_VBDSF=on&var_VDDSF=on&var_TMP=on&var_WIND=on&subregion=&leftlon=-90.5&rightlon=-80.5&toplat=35.2&bottomlat=30 failed with code 404, retrying
2021-07-23 16:02:07,286 WARNING Request to https://nomads.ncep.noaa.gov/cgi-bin/filter_hrrr_sub.pl?file=hrrr.t15z.wrfsubhf08.grib2&dir=/hrrr.20210723/conus&lev_2_m_above_ground=on&lev_10_m_above_ground=on&lev_entire_atmosphere=on&lev_surface=on&var_DSWRF=on&var_VBDSF=on&var_VDDSF=on&var_TMP=on&var_WIND=on&subregion=&leftlon=-90.5&rightlon=-80.5&toplat=35.2&bottomlat=30 failed with code 404, retrying
2021-07-23 16:03:06,453 WARNING Request to https://nomads.ncep.noaa.gov/cgi-bin/filter_hrrr_sub.pl?file=hrrr.t15z.wrfsubhf07.grib2&dir=/hrrr.20210723/conus&lev_2_m_above_ground=on&lev_10_m_above_ground=on&lev_entire_atmosphere=on&lev_surface=on&var_DSWRF=on&var_VBDSF=on&var_VDDSF=on&var_TMP=on&var_WIND=on&subregion=&leftlon=-90.5&rightlon=-80.5&toplat=35.2&bottomlat=30 failed with code 404, retrying
2021-07-23 16:03:06,454 ERROR Aborting on error
Traceback (most recent call last):
  File "/home/pi/test_venv/lib/python3.7/site-packages/solarforecastarbiter/io/fetch/__init__.py", line 54, in wrapper
    ret = await f(*args, **kwargs)
  File "/home/pi/test_venv/lib/python3.7/site-packages/solarforecastarbiter/io/fetch/nwp.py", line 484, in fetch_grib_files
    await get_with_retries(_get_file, session, url, params, tmpfile, chunksize)
  File "/home/pi/test_venv/lib/python3.7/site-packages/solarforecastarbiter/io/fetch/nwp.py", line 271, in get_with_retries
    res = await get_func(*args, **kwargs)
  File "/home/pi/test_venv/lib/python3.7/site-packages/solarforecastarbiter/io/fetch/nwp.py", line 438, in _get_file
    timeout=timeout) as r:
  File "/home/pi/test_venv/lib/python3.7/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/pi/test_venv/lib/python3.7/site-packages/aiohttp/client.py", line 625, in _request
    resp.raise_for_status()
  File "/home/pi/test_venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    headers=self.headers,
aiohttp.client_exceptions.ClientResponseError: 404, message='data file not present', url=URL('https://nomads.ncep.noaa.gov/cgi-bin/filter_hrrr_sub.pl?file=hrrr.t15z.wrfsubhf07.grib2&dir=/hrrr.20210723/conus&lev_2_m_above_ground=on&lev_10_m_above_ground=on&lev_entire_atmosphere=on&lev_surface=on&var_DSWRF=on&var_VBDSF=on&var_VDDSF=on&var_TMP=on&var_WIND=on&subregion=&leftlon=-90.5&rightlon=-80.5&toplat=35.2&bottomlat=30')
2021-07-23 16:08:11,065 INFO Fetching NWP forecasts for hrrr_subhourly
2021-07-23 16:08:11,405 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf07.grib2
2021-07-23 16:08:11,460 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf08.grib2
2021-07-23 16:10:12,050 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf09.grib2
2021-07-23 16:12:12,862 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf10.grib2
2021-07-23 16:14:15,161 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf11.grib2
2021-07-23 16:16:15,756 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf12.grib2
2021-07-23 16:18:16,330 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf13.grib2
2021-07-23 16:20:16,730 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf14.grib2
2021-07-23 16:22:17,141 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf15.grib2
2021-07-23 16:24:17,529 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf16.grib2
2021-07-23 16:26:17,921 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf17.grib2
2021-07-23 16:28:19,535 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf18.grib2
2021-07-23 16:28:21,105 INFO Converting GRIB files to NetCDF with wgrib2 
2021-07-23 16:28:29,231 INFO Optimizing NetCDF file to save at /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr_subhourly.nc
2021-07-23 16:28:36,932 INFO Done optimizing NetCDF at /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr_subhourly.nc
2021-07-23 16:28:36,964 INFO Moving on to next model run
2021-07-23 16:28:36,966 INFO Sleeping 983.0s for next model run 
```

- after deleting the folder, running `solararbiter fetchnwp -v --once /home/pi/Downloads/sfa hrrr_subhourly
` resulted in all new files (none 0 kB):

```
pi@raspberrypi:~/Downloads/sfa/hrrr_subhourly/2021/07/23/15 $ ls -l
total 32196
-rw-r--r-- 1 pi pi  705980 Jul 23 16:33 hrrr.t15z.wrfsubhf00.grib2
-rw-r--r-- 1 pi pi 2814134 Jul 23 16:33 hrrr.t15z.wrfsubhf01.grib2
-rw-r--r-- 1 pi pi 2549912 Jul 23 16:33 hrrr.t15z.wrfsubhf02.grib2
-rw-r--r-- 1 pi pi 2559698 Jul 23 16:33 hrrr.t15z.wrfsubhf03.grib2
-rw-r--r-- 1 pi pi 2628200 Jul 23 16:33 hrrr.t15z.wrfsubhf04.grib2
-rw-r--r-- 1 pi pi 2628200 Jul 23 16:33 hrrr.t15z.wrfsubhf05.grib2
-rw-r--r-- 1 pi pi 2637986 Jul 23 16:33 hrrr.t15z.wrfsubhf06.grib2
-rw-r--r-- 1 pi pi 2677130 Jul 23 16:33 hrrr.t15z.wrfsubhf07.grib2
-rw-r--r-- 1 pi pi 2784776 Jul 23 16:33 hrrr.t15z.wrfsubhf08.grib2
-rw-r--r-- 1 pi pi 2628200 Jul 23 16:33 hrrr.t15z.wrfsubhf09.grib2
-rw-r--r-- 1 pi pi 2510768 Jul 23 16:33 hrrr.t15z.wrfsubhf10.grib2
-rw-r--r-- 1 pi pi  759074 Jul 23 16:33 hrrr.t15z.wrfsubhf11.grib2
-rw-r--r-- 1 pi pi  749288 Jul 23 16:33 hrrr.t15z.wrfsubhf12.grib2
-rw-r--r-- 1 pi pi  710144 Jul 23 16:33 hrrr.t15z.wrfsubhf13.grib2
-rw-r--r-- 1 pi pi  749288 Jul 23 16:33 hrrr.t15z.wrfsubhf14.grib2
-rw-r--r-- 1 pi pi  710144 Jul 23 16:33 hrrr.t15z.wrfsubhf15.grib2
-rw-r--r-- 1 pi pi  710144 Jul 23 16:33 hrrr.t15z.wrfsubhf16.grib2
-rw-r--r-- 1 pi pi  710144 Jul 23 16:33 hrrr.t15z.wrfsubhf17.grib2
-rw-r--r-- 1 pi pi  710144 Jul 23 16:33 hrrr.t15z.wrfsubhf18.grib2
```

- and a larger (complete, ~24 MB) NetCDF file:

```
pi@raspberrypi:~/Downloads/sfa/hrrr_subhourly/2021/07/23/15 $ ls -l
total 23956
-rw-r--r-- 1 pi pi 24527266 Jul 23 16:33 hrrr_subhourly.nc
```

- with this verbose output:

```
2021-07-23 16:32:58,729 INFO Fetching NWP forecasts for hrrr_subhourly
2021-07-23 16:32:59,063 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf00.grib2
2021-07-23 16:32:59,111 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf01.grib2
2021-07-23 16:32:59,165 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf02.grib2
2021-07-23 16:32:59,225 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf03.grib2
2021-07-23 16:32:59,275 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf04.grib2
2021-07-23 16:32:59,325 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf05.grib2
2021-07-23 16:32:59,377 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf06.grib2
2021-07-23 16:32:59,428 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf07.grib2
2021-07-23 16:32:59,477 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf08.grib2
2021-07-23 16:32:59,527 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf09.grib2
2021-07-23 16:32:59,575 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf10.grib2
2021-07-23 16:33:01,669 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf11.grib2
2021-07-23 16:33:01,727 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf12.grib2
2021-07-23 16:33:01,783 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf13.grib2
2021-07-23 16:33:01,835 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf14.grib2
2021-07-23 16:33:02,056 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf15.grib2
2021-07-23 16:33:03,218 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf16.grib2
2021-07-23 16:33:03,294 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf17.grib2
2021-07-23 16:33:03,434 INFO Getting file /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr.t15z.wrfsubhf18.grib2
2021-07-23 16:33:08,332 INFO Converting GRIB files to NetCDF with wgrib2 
2021-07-23 16:33:17,817 INFO Optimizing NetCDF file to save at /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr_subhourly.nc
2021-07-23 16:33:28,966 INFO Done optimizing NetCDF at /home/pi/Downloads/sfa/hrrr_subhourly/2021/07/23/15/hrrr_subhourly.nc
```

**Comment by wholmgren** [comment]
also related: https://github.com/SolarArbiter/solarforecastarbiter-core/issues/680

**Comment by williamhobbs** [comment]
Adding a note here in case it is useful to someone: I've found that when I need to catch up on fetching NWP files (e.g., when my SD card fills up and I don't notice for a few days and I have to clean things up and get re-started), adding a 120 second pause between `fetchnwp --once` commands for HRRR subhourly files seems to work well at avoiding NOMADS rate limiting. 

In Raspberry PI OS terminal, I run something like:
`x=45; for ((n=0; n < (x / 2); n++)); do solararbiter${IFS}fetchnwp${IFS}-v${IFS}--once${IFS}/home/pi/Downloads/sfa${IFS}hrrr_subhourly; sleep 120; done`

This repeats the command `solararbiter fetchnwp -v --once /home/pi/Downloads/sfa hrrr_subhourly` 45 times, pausing 120 seconds between each run (to try to avoid NOAA download rate limits). The `${IFS}` adds necessary spaces to the command. 

This typically returns 19 .grib2 files, so it may be that about 10 files per minute is below the threshold for getting limited.

**Comment by williamhobbs** [comment]
An additional scenario has come up where this could be useful: following NOMADS outages. On 2022-08-15, portions of NOMADS were down for about 6 hours. Estimated time to full repair was approximately 48 hours.
