### ISSUE TITLE
Chunksize issues fetching RAP

### ISSUE THREAD

**Issue by williamhobbs** [SolarArbiter/solarforecastarbiter-core#699]
If I try to fetch the RAP NWP, I get `ValueError: chunksize cannot exceed dimension size`.
(note that in the example below I reduced the size of DOMAIN in /io/nwp.py, but I don't think that should matter)
(I should also note that I'm running all of this in an atypically install on a Raspberry Pi, so it's possible that the errors are due to that...)

```
solararbiter fetchnwp -v --once /home/pi/Downloads/temp rap
2021-07-26 22:32:34,030 INFO Fetching NWP forecasts for rap
2021-07-26 22:32:36,230 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf00.grib2
2021-07-26 22:32:36,391 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf01.grib2
2021-07-26 22:32:36,561 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf02.grib2
2021-07-26 22:32:36,732 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf03.grib2
2021-07-26 22:32:36,902 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf04.grib2
2021-07-26 22:32:37,083 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf05.grib2
2021-07-26 22:32:37,239 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf06.grib2
2021-07-26 22:32:37,412 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf07.grib2
2021-07-26 22:32:37,578 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf08.grib2
2021-07-26 22:32:37,746 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf09.grib2
2021-07-26 22:32:37,918 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf10.grib2
2021-07-26 22:32:38,086 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf11.grib2
2021-07-26 22:32:38,219 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf12.grib2
2021-07-26 22:32:38,275 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf13.grib2
2021-07-26 22:32:38,391 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf14.grib2
2021-07-26 22:32:38,448 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf15.grib2
2021-07-26 22:32:38,502 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf16.grib2
2021-07-26 22:32:38,563 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf17.grib2
2021-07-26 22:32:38,617 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf18.grib2
2021-07-26 22:32:38,673 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf19.grib2
2021-07-26 22:32:38,725 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf20.grib2
2021-07-26 22:32:38,779 INFO Getting file /home/pi/Downloads/temp/rap/2021/07/25/00/rap.t00z.awp130pgrbf21.grib2
2021-07-26 22:32:41,490 INFO Converting GRIB files to NetCDF with wgrib2 
2021-07-26 22:32:44,308 INFO Optimizing NetCDF file to save at /home/pi/Downloads/temp/rap/2021/07/25/00/rap.nc
2021-07-26 22:32:44,561 ERROR Uncaught exception
loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/pi/test_venv2/lib/python3.7/site-packages/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/pi/test_venv2/lib/python3.7/site-packages/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/pi/test_venv2/lib/python3.7/site-packages/solarforecastarbiter/io/fetch/nwp.py", line 565, in _optimize_netcdf
    encoding=encoding)
  File "/home/pi/test_venv2/lib/python3.7/site-packages/xarray/core/dataset.py", line 1910, in to_netcdf
    invalid_netcdf=invalid_netcdf,
  File "/home/pi/test_venv2/lib/python3.7/site-packages/xarray/backends/api.py", line 1078, in to_netcdf
    dataset, store, writer, encoding=encoding, unlimited_dims=unlimited_dims
  File "/home/pi/test_venv2/lib/python3.7/site-packages/xarray/backends/api.py", line 1124, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/home/pi/test_venv2/lib/python3.7/site-packages/xarray/backends/common.py", line 267, in store
    variables, check_encoding_set, writer, unlimited_dims=unlimited_dims
  File "/home/pi/test_venv2/lib/python3.7/site-packages/xarray/backends/common.py", line 305, in set_variables
    name, v, check, unlimited_dims=unlimited_dims
  File "/home/pi/test_venv2/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 498, in prepare_variable
    fill_value=fill_value,
  File "src/netCDF4/_netCDF4.pyx", line 2748, in netCDF4._netCDF4.Dataset.createVariable
  File "src/netCDF4/_netCDF4.pyx", line 3851, in netCDF4._netCDF4.Variable.__init__
ValueError: chunksize cannot exceed dimension size
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/test_venv2/bin/solararbiter", line 10, in <module>
    sys.exit(cli())
  File "/home/pi/test_venv2/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/test_venv2/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/pi/test_venv2/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/test_venv2/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/test_venv2/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/test_venv2/lib/python3.7/site-packages/solarforecastarbiter/cli.py", line 293, in fetchnwp
    loop.run_until_complete(fut)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/test_venv2/lib/python3.7/site-packages/solarforecastarbiter/io/fetch/nwp.py", line 699, in run
    await _run_loop(session, model, modelpath, chunksize, once, use_tmp)
  File "/home/pi/test_venv2/lib/python3.7/site-packages/solarforecastarbiter/io/fetch/nwp.py", line 678, in _run_loop
    await optimize_netcdf(nctmpfile, finalpath)
  File "/home/pi/test_venv2/lib/python3.7/site-packages/solarforecastarbiter/io/fetch/nwp.py", line 582, in optimize_netcdf
    await run_in_executor(_optimize_netcdf, nctmpfile, tmp_path)
  File "/home/pi/test_venv2/lib/python3.7/site-packages/solarforecastarbiter/io/fetch/__init__.py", line 28, in run_in_executor
    exc, partial(func, *args, **kwargs))
ValueError: chunksize cannot exceed dimension size
```

I received valid files:

```
(test_venv2) pi@raspberrypi:~ $ ls -l /home/pi/Downloads/temp/rap/2021/07/25/00
total 524
-rw-r--r-- 1 pi pi 21286 Jul 26 22:32 rap.t00z.awp130pgrbf00.grib2
-rw-r--r-- 1 pi pi 21286 Jul 26 22:32 rap.t00z.awp130pgrbf01.grib2
-rw-r--r-- 1 pi pi 21286 Jul 26 22:32 rap.t00z.awp130pgrbf02.grib2
-rw-r--r-- 1 pi pi 21286 Jul 26 22:32 rap.t00z.awp130pgrbf03.grib2
-rw-r--r-- 1 pi pi 21286 Jul 26 22:32 rap.t00z.awp130pgrbf04.grib2
-rw-r--r-- 1 pi pi 21286 Jul 26 22:32 rap.t00z.awp130pgrbf05.grib2
-rw-r--r-- 1 pi pi 20858 Jul 26 22:32 rap.t00z.awp130pgrbf06.grib2
-rw-r--r-- 1 pi pi 20858 Jul 26 22:32 rap.t00z.awp130pgrbf07.grib2
-rw-r--r-- 1 pi pi 20858 Jul 26 22:32 rap.t00z.awp130pgrbf08.grib2
-rw-r--r-- 1 pi pi 21286 Jul 26 22:32 rap.t00z.awp130pgrbf09.grib2
-rw-r--r-- 1 pi pi 21286 Jul 26 22:32 rap.t00z.awp130pgrbf10.grib2
-rw-r--r-- 1 pi pi 20858 Jul 26 22:32 rap.t00z.awp130pgrbf11.grib2
-rw-r--r-- 1 pi pi 20858 Jul 26 22:32 rap.t00z.awp130pgrbf12.grib2
-rw-r--r-- 1 pi pi 20858 Jul 26 22:32 rap.t00z.awp130pgrbf13.grib2
-rw-r--r-- 1 pi pi 21286 Jul 26 22:32 rap.t00z.awp130pgrbf14.grib2
-rw-r--r-- 1 pi pi 21286 Jul 26 22:32 rap.t00z.awp130pgrbf15.grib2
-rw-r--r-- 1 pi pi 21286 Jul 26 22:32 rap.t00z.awp130pgrbf16.grib2
-rw-r--r-- 1 pi pi 21287 Jul 26 22:32 rap.t00z.awp130pgrbf17.grib2
-rw-r--r-- 1 pi pi 20859 Jul 26 22:32 rap.t00z.awp130pgrbf18.grib2
-rw-r--r-- 1 pi pi 21287 Jul 26 22:32 rap.t00z.awp130pgrbf19.grib2
-rw-r--r-- 1 pi pi 21287 Jul 26 22:32 rap.t00z.awp130pgrbf20.grib2
-rw-r--r-- 1 pi pi 20430 Jul 26 22:32 rap.t00z.awp130pgrbf21.grib2
```

If I go into /io/fetch/nwp.py and modify the chunksizes in `def _optimize_netcdf(nctmpfile, out_path):` to change `chunksizes.append(50)` to `chunksizes.append(22)` (the number of hours in the dateset), I get a valid-looking result:

```
(test_venv2) pi@raspberrypi:~ $ solararbiter fetchnwp -v --once /home/pi/Downloads/temp rap
2021-07-26 22:39:18,071 INFO Fetching NWP forecasts for rap
2021-07-26 22:39:18,357 INFO Converting GRIB files to NetCDF with wgrib2 
2021-07-26 22:39:21,071 INFO Optimizing NetCDF file to save at /home/pi/Downloads/temp/rap/2021/07/25/00/rap.nc
2021-07-26 22:39:21,341 INFO Done optimizing NetCDF at /home/pi/Downloads/temp/rap/2021/07/25/00/rap.nc
```

I'm getting similar errors with GFS, and I *think* I was having the same issue with GEFS. This has not been a problem for me with NAM and HRRR subhourly.

**Comment by williamhobbs** [comment]
I don't have this issue fetching RAP with the docker image, for what that's worth.

**Comment by wholmgren** [comment]
Thanks @williamhobbs - I'm not sure what to make of this right now but we'll keep an eye out for a solution.
