### ISSUE TITLE
Trouble with access

### ISSUE THREAD

**Issue by MichaelHopwood** [SolarArbiter/solarforecastarbiter-core#809]
I had some code which queried data from the arbiter last year, but I'm noticing that it is failing now. Also, I am seeing that https://solarforecastarbiter.org/ is nonresponsive. What adaptations do we need to make to interact with the arbiter?

```cmd
>>> import os
>>> from solarforecastarbiter.io import api
>>> api.request_cli_access_token(os.environ["SOLARARBITER_USER"], os.environ["SOLARARBITER_PASS"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Users\MichaelHopwood\miniconda3\lib\site-packages\solarforecastarbiter\io\api.py", line 61, in request_cli_access_token
    req.raise_for_status()
  File "E:\Users\MichaelHopwood\miniconda3\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://solarforecastarbiter.auth0.com/oauth/token
```

Using version `solarforecastarbiter==1.0.13`

**Comment by dplarson** [comment]
@MichaelHopwood There have been some infrastructure changes behind the scenes from switching the hosting from University of Arizona (UofA) to EPRI. Part of that process also required UofA deleting existing user data and then folks re-signing up with EPRI's hosted version of the Arbiter. Which means the error you're receiving is because your previous user account is no longer authorized to access the Arbiter.

You can email <forecastarbiter@epri.com> to follow-up on this. But we appreciate your patience as there are multiple things happening in parallel with the Arbiter (e.g., preparation for the [American-Made Net Load Forecasting Prize competition](https://www.herox.com/net-load-forecasting), which will use the Arbiter platform).
